configfile: "config/config.yaml"

include: "rules/testcase_1.smk"
include: "rules/testcase_2.smk"
include: "rules/testcase_6.smk"
include: "rules/testcase_7.smk"
include: "rules/testcase_8.smk"

rule run_testcase_1:
    input:
        rules.testcase_1_all.input ,
rule run_testcase_2:        
    input:
        expand(os.path.join(NC_OUT_DIR, "{filename}.nc4") , filename=all_file_paths)
rule run_testcase_6:        
    input:        
        rules.testcase_6_all.input
rule run_testcase_7:        
    input:
        expand(os.path.join(UPDATED_NC_OUT, "{filename}.nc4"), filename=all_file_paths)
rule run_testcase_8:        
    input:
        rules.testcase_8_all.input
