# Basic configuration file
#---------------------------
testcase_1:
    configurationTables:
        inputs:  'config/testcase_1/inputs.tsv'
        indicators: 'config/testcase_1/indicators.tsv'
        scenarios:  'config/testcase_1/scenarios.tsv'
        periods:  'config/testcase_1/periods.tsv'
        seasons: 'config/testcase_1/seasons.tsv'
    dirs:
        variables: '/lustre/storeC-ext/users/klimakverna/development/output/testcase_1/KAPy_results/1.variables/time_binning_periods/mpi_racmo'
        indicators: '/lustre/storeC-ext/users/klimakverna/development/output/testcase_1/KAPy_results/2.indicators/time_binning_periods/mpi_racmo'
        regridded: '/lustre/storeC-ext/users/klimakverna/development/output/testcase_1/KAPy_results/3.commmon_grid'
        ensstats: '/lustre/storeC-ext/users/klimakverna/development/output/testcase_1/KAPy_results/4.ensstats/time_binning_periods/mpi_racmo'
        arealstats: '/lustre/storeC-ext/users/klimakverna/development/output/testcase_1/KAPy_results/5.areal_statistics/time_binning_periods/mpi_racmo'
        plots: '/lustre/storeC-ext/users/klimakverna/development/output/testcase_1/KAPy_results/6.plots/mpi_racmo'
        netcdf: '/lustre/storeC-ext/users/klimakverna/development/output/testcase_1/KAPy_results/7.netcdf/mpi_racmo'

    # Configuration options------------------------------------
    arealstats:
        calcForMembers: False
    cutouts:
        method: 'lonlatbox'
        xmin: 4.088
        xmax: 31.761
        ymin: 57.759
        ymax: 71.384
    ensembles:
        upperPercentile: 90
        centralPercentile: 50
        lowerPercentile: 10
    outputGrid:
        regriddingEngine: None
testcase_2:        
        input_json: "config/testcase_2/input.json"
        mmd_output: "/lustre/storeC-ext/users/klimakverna/development/output/testcase_2/mmd"
        nc_output: "/lustre/storeC-ext/users/klimakverna/development/output/testcase_2"
        input_base: "/lustre/storeC-ext/users/klimakverna/development/output/testcase_7/"
testcase_6:
    configurationTables:
        inputs:  'config/testcase_6/inputs.tsv'
        indicators: 'config/testcase_6/indicators.tsv'
        scenarios:  'config/testcase_6/scenarios.tsv'
        periods:  'config/testcase_6/periods.tsv'
        seasons: 'config/testcase_6/seasons.tsv'
        region: 'config/testcase_6/region.tsv'
    dirs:
        region: '/lustre/storeC-ext/users/klimakverna/development/output/testcase_6/model_results/ecearth-racmo'

    # Configuration options------------------------------------
    arealstats:
        calcForMembers: False
    cutouts:
        method: 'lonlatbox'
        xmin: 4.088
        xmax: 31.761
        ymin: 57.759
        ymax: 71.384
    ensembles:
        upperPercentile: 90
        centralPercentile: 50
        lowerPercentile: 10
    outputGrid:
        regriddingEngine: None
testcase_7:
        attributes: "config/testcase_7/global_attr.json"
        variables_pr: "config/testcase_7/variable_pr.json"
        index_tasmax20ge: "config/testcase_7/index_tasmax20ge.json"
        30_year_mean: "config/testcase_7/30_year_mean_diff_norheatwave.json"
        updated_nc: "output/testcase_7"
        input_nc: "config/testcase_7/input.json"
        input_base: "/lustre/storeC-ext/users/kin2100/"
testcase_8:
    configurationTables:
        inputs:  'config/testcase_8/inputs.tsv'
        indicators: 'config/testcase_8/indicators.tsv'
        scenarios:  'config/testcase_8/scenarios.tsv'
        periods:  'config/testcase_8/periods.tsv'
        seasons: 'config/testcase_8/seasons.tsv'
        region: 'config/testcase_8/region.tsv'
    dirs:
        region: '/lustre/storeC-ext/users/klimakverna/development/output/testcase_8/model_results/EQM/ecearth_racmo'
        csv: '/lustre/storeC-ext/users/klimakverna/development/output/testcase_8/model_results/EQM/ecearth_racmo'

    # Configuration options------------------------------------
    arealstats:
        calcForMembers: False
    cutouts:
        method: 'lonlatbox'
        xmin: 4.088
        xmax: 31.761
        ymin: 57.759
        ymax: 71.384
    ensembles:
        upperPercentile: 90
        centralPercentile: 50
        lowerPercentile: 10
    outputGrid:
        regriddingEngine: None
