# Basic configuration file
#---------------------------
testcase_1:
    configurationTables:
        inputs:  'config/inputs.tsv'
        indicators: 'config/indicators.tsv'
        scenarios:  'config/scenarios.tsv'
        periods:  'config/periods.tsv'
        seasons: 'config/seasons.tsv'
    dirs:
        variables: '/lustre/storeC-ext/users/klimakverna/development/output/testcase_1/1.variables/time_binning_periods/noresm_hclim'
        indicators: '/lustre/storeC-ext/users/klimakverna/development/output/testcase_1/2.indicators/time_binning_periods/noresm_hclim'
        regridded: '/lustre/storeC-ext/users/klimakverna/development/output/testcase_1/3.commmon_grid'
        ensstats: '/lustre/storeC-ext/users/klimakverna/development/output/testcase_1/4.ensstats/time_binning_periods/noresm_hclim'
        arealstats: '/lustre/storeC-ext/users/klimakverna/development/output/testcase_1/5.areal_statistics/time_binning_periods/noresm_hclim'
        plots: '/lustre/storeC-ext/users/klimakverna/development/output/testcase_1/6.plots/noresm_hclim'
        netcdf: '/lustre/storeC-ext/users/klimakverna/development/output/testcase_1/7.netcdf/noresm_hclim'

    # Configuration options------------------------------------
    arealstats:
        calcForMembers: False
    cutouts:
        method: 'lonlatbox'
        xmin: 4.088
        xmax: 31.761
        ymin: 57.759
        ymax: 71.384
    ensembles:
        upperPercentile: 90
        centralPercentile: 50
        lowerPercentile: 10
    outputGrid:
        regriddingEngine: None
testcase_2:        
        input_json: "config/testcase_2.json"
        mmd_output: "/lustre/storeC-ext/users/klimakverna/development/output/testcase_2/mmd"
        nc_output: "/lustre/storeC-ext/users/klimakverna/development/output/testcase_2"
        input_base: "/lustre/storeC-ext/users/klimakverna/development/output/testcase_2/"

testcase_7:
        attributes: "config/testcase_7/global_attr.json"
        variables_pr: "config/testcase_7/variable_pr.json"
        index_tasmax20ge: "config/testcase_7/index_tasmax20ge.json"
        30_year_mean: "config/testcase_7/30_year_mean_diff_norheatwave.json"
        updated_nc: "output/testcase_7"
        input_nc: "config/testcase_7/input.json"
        input_base: "/home/shamlym/workspace/klima-kverna/nc/"
