testcase_1:
  arealstats:
    calcForMembers: false
  configurationTables:
    indicators: config/testcase_1/indicators.tsv
    inputs: config/testcase_1/inputs.tsv
    periods: config/testcase_1/periods.tsv
    scenarios: config/testcase_1/scenarios.tsv
    seasons: config/testcase_1/seasons.tsv
  cutouts:
    method: lonlatbox
    xmax: 31.761
    xmin: 4.088
    ymax: 71.384
    ymin: 57.759
  dirs:
    arealstats: /lustre/storeC-ext/users/klimakverna/development/output/testcase_1/KAPy_results/5.areal_statistics/time_binning_periods/mpi_racmo
    ensstats: /lustre/storeC-ext/users/klimakverna/development/output/testcase_1/KAPy_results/4.ensstats/time_binning_periods/mpi_racmo
    indicators: /lustre/storeC-ext/users/klimakverna/development/output/testcase_1/KAPy_results/2.indicators/time_binning_periods/mpi_racmo
    netcdf: /lustre/storeC-ext/users/klimakverna/development/output/testcase_1/KAPy_results/7.netcdf/mpi_racmo
    plots: /lustre/storeC-ext/users/klimakverna/development/output/testcase_1/KAPy_results/6.plots/mpi_racmo
    regridded: /lustre/storeC-ext/users/klimakverna/development/output/testcase_1/KAPy_results/3.commmon_grid
    variables: /lustre/storeC-ext/users/klimakverna/development/output/testcase_1/KAPy_results/1.variables/time_binning_periods/mpi_racmo
  ensembles:
    centralPercentile: 50
    lowerPercentile: 10
    upperPercentile: 90
  outputGrid:
    regriddingEngine: None
testcase_2:
  input_base: /lustre/storeC-ext/users/klimakverna/development/output/testcase_2/
  input_json: /lustre/storeC-ext/users/klimakverna/development/Klimakverna-Pilot1/config/testcase_2.json
  mmd_output: /lustre/storeC-ext/users/klimakverna/development/output/testcase_2/mmd
  nc_output: /lustre/storeC-ext/users/klimakverna/development/output/testcase_2
testcase_6:
  arealstats:
    calcForMembers: false
  configurationTables:
    indicators: config/testcase_6/indicators.tsv
    inputs: config/testcase_6/inputs.tsv
    periods: config/testcase_6/periods.tsv
    region: config/testcase_6/region.tsv
    scenarios: config/testcase_6/scenarios.tsv
    seasons: config/testcase_6/seasons.tsv
  cutouts:
    method: lonlatbox
    xmax: 31.761
    xmin: 4.088
    ymax: 71.384
    ymin: 57.759
  dirs:
    region: /lustre/storeC-ext/users/klimakverna/development/output/testcase_6/model_results/ecearth-racmo
  ensembles:
    centralPercentile: 50
    lowerPercentile: 10
    upperPercentile: 90
  outputGrid:
    regriddingEngine: None
testcase_7:
  30_year_mean: config/testcase_7/30_year_mean_diff_norheatwave.json
  attributes: config/testcase_7/global_attr.json
  index_tasmax20ge: config/testcase_7/index_tasmax20ge.json
  input_base: /lustre/storeC-ext/users/kin2100/
  input_nc: config/testcase_7/input.json
  updated_nc: output/testcase_7
  variables_pr: config/testcase_7/variable_pr.json
testcase_8:
  arealstats:
    calcForMembers: false
  configurationTables:
    indicators: /lustre/storeC-ext/users/klimakverna/development/Klimakverna-Pilot1/config/testcase_8/indicators.tsv
    inputs: /lustre/storeC-ext/users/klimakverna/development/Klimakverna-Pilot1/config/testcase_8/inputs.tsv
    periods: /lustre/storeC-ext/users/klimakverna/development/Klimakverna-Pilot1/config/testcase_8/periods.tsv
    region: config/testcase_8/region.tsv
    scenarios: /lustre/storeC-ext/users/klimakverna/development/Klimakverna-Pilot1/config/testcase_8/scenarios.tsv
    seasons: /lustre/storeC-ext/users/klimakverna/development/Klimakverna-Pilot1/config/testcase_8/seasons.tsv
  cutouts:
    method: lonlatbox
    xmax: 31.761
    xmin: 4.088
    ymax: 71.384
    ymin: 57.759
  dirs:
    csv: /lustre/storeC-ext/users/klimakverna/development/output/testcase_8/model_results/3DBC/30y/cnrm_aladin
    region: /lustre/storeC-ext/users/klimakverna/development/output/testcase_8/model_results/3DBC/30y/cnrm_aladin
  ensembles:
    centralPercentile: 50
    lowerPercentile: 10
    upperPercentile: 90
  outputGrid:
    regriddingEngine: None
